### ISSUE TITLE
Add a TOC

### ISSUE THREAD

**Issue by oliverguhr** [teaching-ml/2020#14]
Check if we can use:
1. Using kramdown's {:toc} option
2. or https://github.com/timkahlke/jekyll-toc

**Comment by oliverguhr** [comment]
@psteinb Added a toc. Feel free to comment or close the issue.

**Comment by psteinb** [comment]
Wonderful. I appreciate that greatly. My TODOs are again at the self-drowning level.

**Comment by psteinb** [comment]
Can't close the issue though for some reason. :shrug:
