### ISSUE TITLE
publish satellite event recording

### ISSUE THREAD

**Issue by oliverguhr** [teaching-ml/2020#20]
Hello Heidi,
could you please:

* Upload recording to Youtube
* Post Youtube link here

**Comment by HeidiSeibold** [comment]
Will do

Channel: https://www.youtube.com/channel/UCJWzJlUp-iZtCMhsohvExPA
Playlist (WIP): https://youtu.be/4xUhFW1wv24

**Comment by HeidiSeibold** [comment]
Playlist is ready now (link has changed). Took more effort to cut&edit than expected...

https://www.youtube.com/playlist?list=PLdDZRjAdquEN3PXbzX4cUKXCFDR_vNo8O

Can you add it to the webiste @oliverguhr ?

**Comment by oliverguhr** [comment]
Thank you @HeidiSeibold I will add this to the website.

**Comment by HeidiSeibold** [comment]
@oliverguhr @psteinb should we add a note on the website that it would be beneficial if workshop participants could watch the videos beforehand? Is there any way for us to send them a message? (maybe at least a message to authors and reviewer might be nice)

**Comment by oliverguhr** [comment]
> @oliverguhr @psteinb should we add a note on the website that it would be beneficial if workshop participants could watch the videos beforehand? Is there any way for us to send them a message? (maybe at least a message to authors and reviewer might be nice)

Good question - lets discuss this today.

**Comment by psteinb** [comment]
I think, we should add a corresponding note on the website and in the etherpad we use. I can try to contact all
reviewers/authors today through openreview.net. twitter comes to mind as well.
