### ISSUE TITLE
Publish slides from the satellite event

### ISSUE THREAD

**Issue by oliverguhr** [teaching-ml/2020#21]
* Collect Links
* Post them on the main page

**Comment by oliverguhr** [comment]
@psteinb and @HeidiSeibold 

Could you please post the links to your slides here? Thx!

**Comment by psteinb** [comment]
For now our slides are available at:
https://codimd.carpentries.org/p/GfvkCWTYA#/
feel free to use it for now.

In due course, I plan to upload my slidedeck to zenodo and get a DOI. I'll update the page once I have this, so the slides are
citable.

**Comment by HeidiSeibold** [comment]
https://tinyurl.com/teachingML
